# Generated by Django 5.2.4 on 2026-04-15 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата и время создания проекта', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, help_text='Введите описание проекта (необязательно)', verbose_name='Описание проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, help_text='Введите URL репозитория на GitHub (необязательно)', verbose_name='URL репозитория на GitHub'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text='Введите название проекта (до 200 символов)', max_length=200, verbose_name='Название проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', help_text='Выберите статус проекта', max_length=6, verbose_name='Статус проекта'),
        ),
    ]
